# This is a basic workflow to help you get started with Actions

name: TRIGGER

on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: repo dispatch
        run: |
          curl -X POST https://api.github.com/repos/sasovdmitri/to/dispatches \
          -H 'Accept: application/vnd.github+json' \
          -u ${{ secrets.ACCESS_TOKEN }} 
          --data '{"event_type": "test"}'
